### PR TITLE
DLT Template

### PR DESCRIPTION
**Pull request by hironate**
DLT Template ID in options

### CODE REVIEW

**Comment by robincsamuel** [comment]
@Hironate Thanks for the PR. Could you please add the same in the [default config](https://github.com/robincsamuel/laravel-msg91/blob/master/src/config/config.php) as well?

**Comment by hironate** [comment]
@robincsamuel dlt id is dynamic differs from template to template, so no need to add into config

**Comment by robincsamuel** [comment]
@Hironate I understand how DLT works, and so is every other config including `sender_id`, `auth_key` etc. And yet, we do have those in the config file. I request you to please have a look at the config file I shared above. The idea is to keep placeholders so that the next person knows the config allows them to set DLT.

If the config doesn't have the `dlt` key mentioned, how'd anyone assume if there's a provision or not?

**Comment by abhiburk** [comment]
Any update on this ?

**Comment by robincsamuel** [comment]
@abhiburk As you can see in the previous comments, I'm waiting for a few small changes to merge this.

**Comment by smarteertech** [comment]
I think DLT_TE_ID params will be sent as an option while sending a request to MSG.

**Comment by robincsamuel** [comment]
@smarteertech I get it now, my understanding was different. Sorry about that, wasn't following msg91 for a while.

I see `DLT` is the template id. However, if there is a template, why we need a message text?. So instead of just including another key, let's figure out the best way to achieve that.

**Comment by smarteertech** [comment]
The template has dynamic elements, we need to register that template and mention where the dynamic element placed inside a message on a telecommunication channel like Jio network. Once the template approved, we need to send DLT_TE_ID along with the message, of course, the message should match with the template that was approved.

**Comment by robincsamuel** [comment]
And still, need to pass the entire message text? Sharing an example would make it easier for me to understand :)

**Comment by smarteertech** [comment]
Yes, adding another example below
`            $customerMessage = "Thank you for booking.";
           LaravelMsg91::message($journey->customer_phone, $customerMessage, array('DLT_TE_ID' => '123456798132465798'));`

**Comment by robincsamuel** [comment]
Thanks, I'm merging this.

**Pull request merged**
